---
- name: Materialize the spark upstart script
  template: src=spark-master.conf dest=/etc/init/spark-master.conf backup=yes mode=0644

- name: Materialize the spark-submit-local script
  template: src=spark-submit-local dest=/opt/spark/bin/spark-submit-local backup=yes mode=0755
